INSERT INTO PRODUCT VALUES (1, '상품명1','100');
INSERT INTO PRODUCT VALUES (2, '상품명2','200');
INSERT INTO PRODUCT VALUES (3, '상품명3','300');
INSERT INTO PRODUCT VALUES (4, '상품명4','400');
INSERT INTO PRODUCT VALUES (5, '상품명5','500');
INSERT INTO PRODUCT VALUES (6, '상품명6','600');
INSERT INTO PRODUCT VALUES (7, '상품명7','700');
INSERT INTO PRODUCT VALUES (8, '상품명8','800');



INSERT INTO REVIEW VALUES (1, 1, '상품평1','1');
INSERT INTO REVIEW VALUES (2, 2, '상품평2','2');
INSERT INTO REVIEW VALUES (3, 3, '상품평3','3');
INSERT INTO REVIEW VALUES (4, 4, '상품평4','4');
INSERT INTO REVIEW VALUES (5, 5, '상품평5','5');
INSERT INTO REVIEW VALUES (6, 6, '상품평6','4');
INSERT INTO REVIEW VALUES (7, 7, '상품평7','3');
INSERT INTO REVIEW VALUES (8, 8, '상품평8','2');

